//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Makolab.Fractus.Kernel.KernelTester.WcfKernelService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfKernelService.IKernelService")]
    public interface IKernelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/LogOn", ReplyAction="http://tempuri.org/IKernelService/LogOnResponse")]
        string LogOn(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/LogOff", ReplyAction="http://tempuri.org/IKernelService/LogOffResponse")]
        void LogOff();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetVersion", ReplyAction="http://tempuri.org/IKernelService/GetVersionResponse")]
        string GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/Delay", ReplyAction="http://tempuri.org/IKernelService/DelayResponse")]
        string Delay(int mills);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetConfiguration", ReplyAction="http://tempuri.org/IKernelService/GetConfigurationResponse")]
        string GetConfiguration(string keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetConfigurationByBranch", ReplyAction="http://tempuri.org/IKernelService/GetConfigurationByBranchResponse")]
        string GetConfigurationByBranch(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetConfigurationKeys", ReplyAction="http://tempuri.org/IKernelService/GetConfigurationKeysResponse")]
        string GetConfigurationKeys();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/SaveConfiguration", ReplyAction="http://tempuri.org/IKernelService/SaveConfigurationResponse")]
        string SaveConfiguration(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/SaveConfigurationByBranch", ReplyAction="http://tempuri.org/IKernelService/SaveConfigurationByBranchResponse")]
        string SaveConfigurationByBranch(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/CreateNewBusinessObject", ReplyAction="http://tempuri.org/IKernelService/CreateNewBusinessObjectResponse")]
        string CreateNewBusinessObject(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/SaveBusinessObject", ReplyAction="http://tempuri.org/IKernelService/SaveBusinessObjectResponse")]
        string SaveBusinessObject(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetDocuments", ReplyAction="http://tempuri.org/IKernelService/GetDocumentsResponse")]
        string GetDocuments(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetContractors", ReplyAction="http://tempuri.org/IKernelService/GetContractorsResponse")]
        string GetContractors(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetFileDescriptors", ReplyAction="http://tempuri.org/IKernelService/GetFileDescriptorsResponse")]
        string GetFileDescriptors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetOwnCompanies", ReplyAction="http://tempuri.org/IKernelService/GetOwnCompaniesResponse")]
        string GetOwnCompanies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetItems", ReplyAction="http://tempuri.org/IKernelService/GetItemsResponse")]
        string GetItems(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetProductionItems", ReplyAction="http://tempuri.org/IKernelService/GetProductionItemsResponse")]
        string GetProductionItems(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetDictionaries", ReplyAction="http://tempuri.org/IKernelService/GetDictionariesResponse")]
        string GetDictionaries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/LoadBusinessObject", ReplyAction="http://tempuri.org/IKernelService/LoadBusinessObjectResponse")]
        string LoadBusinessObject(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetLogByDate", ReplyAction="http://tempuri.org/IKernelService/GetLogByDateResponse")]
        string GetLogByDate(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/DeleteBusinessObject", ReplyAction="http://tempuri.org/IKernelService/DeleteBusinessObjectResponse")]
        string DeleteBusinessObject(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetHttpResponse", ReplyAction="http://tempuri.org/IKernelService/GetHttpResponseResponse")]
        string GetHttpResponse(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/CreateItemEquivalentGroup", ReplyAction="http://tempuri.org/IKernelService/CreateItemEquivalentGroupResponse")]
        string CreateItemEquivalentGroup(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/CreateItemEquivalent", ReplyAction="http://tempuri.org/IKernelService/CreateItemEquivalentResponse")]
        string CreateItemEquivalent(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/RemoveItemFromEquivalentGroup", ReplyAction="http://tempuri.org/IKernelService/RemoveItemFromEquivalentGroupResponse")]
        string RemoveItemFromEquivalentGroup(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/RemoveItemFromEquivalent", ReplyAction="http://tempuri.org/IKernelService/RemoveItemFromEquivalentResponse")]
        string RemoveItemFromEquivalent(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/CreateItemsBarcodes", ReplyAction="http://tempuri.org/IKernelService/CreateItemsBarcodesResponse")]
        string CreateItemsBarcodes(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/LoadDictionary", ReplyAction="http://tempuri.org/IKernelService/LoadDictionaryResponse")]
        string LoadDictionary(string dictionary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/SaveDictionary", ReplyAction="http://tempuri.org/IKernelService/SaveDictionaryResponse")]
        string SaveDictionary(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetDictionariesVersion", ReplyAction="http://tempuri.org/IKernelService/GetDictionariesVersionResponse")]
        int GetDictionariesVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetFreeDocumentNumber", ReplyAction="http://tempuri.org/IKernelService/GetFreeDocumentNumberResponse")]
        string GetFreeDocumentNumber(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetTemplates", ReplyAction="http://tempuri.org/IKernelService/GetTemplatesResponse")]
        string GetTemplates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/CheckNumberExistence", ReplyAction="http://tempuri.org/IKernelService/CheckNumberExistenceResponse")]
        bool CheckNumberExistence(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetRandomContractors", ReplyAction="http://tempuri.org/IKernelService/GetRandomContractorsResponse")]
        string GetRandomContractors(string amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetRandomCommercialDocumentLines", ReplyAction="http://tempuri.org/IKernelService/GetRandomCommercialDocumentLinesResponse")]
        string GetRandomCommercialDocumentLines(string amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetRandomWarehouseDocumentLines", ReplyAction="http://tempuri.org/IKernelService/GetRandomWarehouseDocumentLinesResponse")]
        string GetRandomWarehouseDocumentLines(string amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetRandomKeywords", ReplyAction="http://tempuri.org/IKernelService/GetRandomKeywordsResponse")]
        string GetRandomKeywords(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/ExecuteCustomProcedure", ReplyAction="http://tempuri.org/IKernelService/ExecuteCustomProcedureResponse")]
        string ExecuteCustomProcedure(string procedureName, string parameterXml, string outputFormat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/RelateCommercialDocumentToWarehouseDocuments", ReplyAction="http://tempuri.org/IKernelService/RelateCommercialDocumentToWarehouseDocumentsRes" +
            "ponse")]
        string RelateCommercialDocumentToWarehouseDocuments(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/UnrelateCommercialDocumentFromWarehouseDocument" +
            "s", ReplyAction="http://tempuri.org/IKernelService/UnrelateCommercialDocumentFromWarehouseDocument" +
            "sResponse")]
        string UnrelateCommercialDocumentFromWarehouseDocuments(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/ChangeDocumentStatus", ReplyAction="http://tempuri.org/IKernelService/ChangeDocumentStatusResponse")]
        string ChangeDocumentStatus(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/FiscalizeCommercialDocument", ReplyAction="http://tempuri.org/IKernelService/FiscalizeCommercialDocumentResponse")]
        string FiscalizeCommercialDocument(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetUserLanguageVersion", ReplyAction="http://tempuri.org/IKernelService/GetUserLanguageVersionResponse")]
        string GetUserLanguageVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/TestProc", ReplyAction="http://tempuri.org/IKernelService/TestProcResponse")]
        string TestProc(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetContractorDealing", ReplyAction="http://tempuri.org/IKernelService/GetContractorDealingResponse")]
        string GetContractorDealing(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetPermissionProfiles", ReplyAction="http://tempuri.org/IKernelService/GetPermissionProfilesResponse")]
        string GetPermissionProfiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetWarehouseDocumentLinesTree", ReplyAction="http://tempuri.org/IKernelService/GetWarehouseDocumentLinesTreeResponse")]
        string GetWarehouseDocumentLinesTree(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetOpenedFinancialReport", ReplyAction="http://tempuri.org/IKernelService/GetOpenedFinancialReportResponse")]
        string GetOpenedFinancialReport(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/CreateTask", ReplyAction="http://tempuri.org/IKernelService/CreateTaskResponse")]
        string CreateTask(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/QueryTask", ReplyAction="http://tempuri.org/IKernelService/QueryTaskResponse")]
        string QueryTask(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetTaskResult", ReplyAction="http://tempuri.org/IKernelService/GetTaskResultResponse")]
        string GetTaskResult(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/TerminateTask", ReplyAction="http://tempuri.org/IKernelService/TerminateTaskResponse")]
        string TerminateTask(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/SaveWarehouseMap", ReplyAction="http://tempuri.org/IKernelService/SaveWarehouseMapResponse")]
        string SaveWarehouseMap(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetItemsDetails", ReplyAction="http://tempuri.org/IKernelService/GetItemsDetailsResponse")]
        string GetItemsDetails(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/LoadShiftTransactionByShiftId", ReplyAction="http://tempuri.org/IKernelService/LoadShiftTransactionByShiftIdResponse")]
        string LoadShiftTransactionByShiftId(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetDocumentOperations", ReplyAction="http://tempuri.org/IKernelService/GetDocumentOperationsResponse")]
        string GetDocumentOperations(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/ChangeProcessState", ReplyAction="http://tempuri.org/IKernelService/ChangeProcessStateResponse")]
        string ChangeProcessState(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/UpdateItemCataloguePrices", ReplyAction="http://tempuri.org/IKernelService/UpdateItemCataloguePricesResponse")]
        string UpdateItemCataloguePrices(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/SavePivotReport", ReplyAction="http://tempuri.org/IKernelService/SavePivotReportResponse")]
        string SavePivotReport(System.IO.Stream formsData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetPivotReport", ReplyAction="http://tempuri.org/IKernelService/GetPivotReportResponse")]
        System.IO.Stream GetPivotReport(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKernelService/GetPivotReportsList", ReplyAction="http://tempuri.org/IKernelService/GetPivotReportsListResponse")]
        string GetPivotReportsList();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKernelServiceChannel : Makolab.Fractus.Kernel.KernelTester.WcfKernelService.IKernelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KernelServiceClient : System.ServiceModel.ClientBase<Makolab.Fractus.Kernel.KernelTester.WcfKernelService.IKernelService>, Makolab.Fractus.Kernel.KernelTester.WcfKernelService.IKernelService {
        
        public KernelServiceClient() {
        }
        
        public KernelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KernelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KernelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KernelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string LogOn(string requestXml) {
            return base.Channel.LogOn(requestXml);
        }
        
        public void LogOff() {
            base.Channel.LogOff();
        }
        
        public string GetVersion() {
            return base.Channel.GetVersion();
        }
        
        public string Delay(int mills) {
            return base.Channel.Delay(mills);
        }
        
        public string GetConfiguration(string keys) {
            return base.Channel.GetConfiguration(keys);
        }
        
        public string GetConfigurationByBranch(string requestXml) {
            return base.Channel.GetConfigurationByBranch(requestXml);
        }
        
        public string GetConfigurationKeys() {
            return base.Channel.GetConfigurationKeys();
        }
        
        public string SaveConfiguration(string requestXml) {
            return base.Channel.SaveConfiguration(requestXml);
        }
        
        public string SaveConfigurationByBranch(string requestXml) {
            return base.Channel.SaveConfigurationByBranch(requestXml);
        }
        
        public string CreateNewBusinessObject(string requestXml) {
            return base.Channel.CreateNewBusinessObject(requestXml);
        }
        
        public string SaveBusinessObject(string requestXml) {
            return base.Channel.SaveBusinessObject(requestXml);
        }
        
        public string GetDocuments(string requestXml) {
            return base.Channel.GetDocuments(requestXml);
        }
        
        public string GetContractors(string requestXml) {
            return base.Channel.GetContractors(requestXml);
        }
        
        public string GetFileDescriptors() {
            return base.Channel.GetFileDescriptors();
        }
        
        public string GetOwnCompanies() {
            return base.Channel.GetOwnCompanies();
        }
        
        public string GetItems(string requestXml) {
            return base.Channel.GetItems(requestXml);
        }
        
        public string GetProductionItems(string requestXml) {
            return base.Channel.GetProductionItems(requestXml);
        }
        
        public string GetDictionaries() {
            return base.Channel.GetDictionaries();
        }
        
        public string LoadBusinessObject(string requestXml) {
            return base.Channel.LoadBusinessObject(requestXml);
        }
        
        public string GetLogByDate(string date) {
            return base.Channel.GetLogByDate(date);
        }
        
        public string DeleteBusinessObject(string requestXml) {
            return base.Channel.DeleteBusinessObject(requestXml);
        }
        
        public string GetHttpResponse(string url) {
            return base.Channel.GetHttpResponse(url);
        }
        
        public string CreateItemEquivalentGroup(string requestXml) {
            return base.Channel.CreateItemEquivalentGroup(requestXml);
        }
        
        public string CreateItemEquivalent(string requestXml) {
            return base.Channel.CreateItemEquivalent(requestXml);
        }
        
        public string RemoveItemFromEquivalentGroup(string requestXml) {
            return base.Channel.RemoveItemFromEquivalentGroup(requestXml);
        }
        
        public string RemoveItemFromEquivalent(string requestXml) {
            return base.Channel.RemoveItemFromEquivalent(requestXml);
        }
        
        public string CreateItemsBarcodes(string requestXml) {
            return base.Channel.CreateItemsBarcodes(requestXml);
        }
        
        public string LoadDictionary(string dictionary) {
            return base.Channel.LoadDictionary(dictionary);
        }
        
        public string SaveDictionary(string requestXml) {
            return base.Channel.SaveDictionary(requestXml);
        }
        
        public int GetDictionariesVersion() {
            return base.Channel.GetDictionariesVersion();
        }
        
        public string GetFreeDocumentNumber(string requestXml) {
            return base.Channel.GetFreeDocumentNumber(requestXml);
        }
        
        public string GetTemplates() {
            return base.Channel.GetTemplates();
        }
        
        public bool CheckNumberExistence(string requestXml) {
            return base.Channel.CheckNumberExistence(requestXml);
        }
        
        public string GetRandomContractors(string amount) {
            return base.Channel.GetRandomContractors(amount);
        }
        
        public string GetRandomCommercialDocumentLines(string amount) {
            return base.Channel.GetRandomCommercialDocumentLines(amount);
        }
        
        public string GetRandomWarehouseDocumentLines(string amount) {
            return base.Channel.GetRandomWarehouseDocumentLines(amount);
        }
        
        public string GetRandomKeywords(string requestXml) {
            return base.Channel.GetRandomKeywords(requestXml);
        }
        
        public string ExecuteCustomProcedure(string procedureName, string parameterXml, string outputFormat) {
            return base.Channel.ExecuteCustomProcedure(procedureName, parameterXml, outputFormat);
        }
        
        public string RelateCommercialDocumentToWarehouseDocuments(string requestXml) {
            return base.Channel.RelateCommercialDocumentToWarehouseDocuments(requestXml);
        }
        
        public string UnrelateCommercialDocumentFromWarehouseDocuments(string requestXml) {
            return base.Channel.UnrelateCommercialDocumentFromWarehouseDocuments(requestXml);
        }
        
        public string ChangeDocumentStatus(string requestXml) {
            return base.Channel.ChangeDocumentStatus(requestXml);
        }
        
        public string FiscalizeCommercialDocument(string requestXml) {
            return base.Channel.FiscalizeCommercialDocument(requestXml);
        }
        
        public string GetUserLanguageVersion() {
            return base.Channel.GetUserLanguageVersion();
        }
        
        public string TestProc(string xml) {
            return base.Channel.TestProc(xml);
        }
        
        public string GetContractorDealing(string requestXml) {
            return base.Channel.GetContractorDealing(requestXml);
        }
        
        public string GetPermissionProfiles() {
            return base.Channel.GetPermissionProfiles();
        }
        
        public string GetWarehouseDocumentLinesTree(string requestXml) {
            return base.Channel.GetWarehouseDocumentLinesTree(requestXml);
        }
        
        public string GetOpenedFinancialReport(string requestXml) {
            return base.Channel.GetOpenedFinancialReport(requestXml);
        }
        
        public string CreateTask(string requestXml) {
            return base.Channel.CreateTask(requestXml);
        }
        
        public string QueryTask(string requestXml) {
            return base.Channel.QueryTask(requestXml);
        }
        
        public string GetTaskResult(string requestXml) {
            return base.Channel.GetTaskResult(requestXml);
        }
        
        public string TerminateTask(string requestXml) {
            return base.Channel.TerminateTask(requestXml);
        }
        
        public string SaveWarehouseMap(string requestXml) {
            return base.Channel.SaveWarehouseMap(requestXml);
        }
        
        public string GetItemsDetails(string requestXml) {
            return base.Channel.GetItemsDetails(requestXml);
        }
        
        public string LoadShiftTransactionByShiftId(string requestXml) {
            return base.Channel.LoadShiftTransactionByShiftId(requestXml);
        }
        
        public string GetDocumentOperations(string requestXml) {
            return base.Channel.GetDocumentOperations(requestXml);
        }
        
        public string ChangeProcessState(string requestXml) {
            return base.Channel.ChangeProcessState(requestXml);
        }
        
        public string UpdateItemCataloguePrices(string requestXml) {
            return base.Channel.UpdateItemCataloguePrices(requestXml);
        }
        
        public string SavePivotReport(System.IO.Stream formsData) {
            return base.Channel.SavePivotReport(formsData);
        }
        
        public System.IO.Stream GetPivotReport(string id) {
            return base.Channel.GetPivotReport(id);
        }
        
        public string GetPivotReportsList() {
            return base.Channel.GetPivotReportsList();
        }
    }
}
