//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzTest.Makolab.Fractus.Communication {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Makolab.Fractus.Communication.ISynchronizationService")]
    public interface ISynchronizationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronizationService/GetData", ReplyAction="http://tempuri.org/ISynchronizationService/GetDataResponse")]
        System.ServiceModel.Channels.Message GetData(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronizationService/SendData", ReplyAction="http://tempuri.org/ISynchronizationService/SendDataResponse")]
        System.ServiceModel.Channels.Message SendData(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISynchronizationServiceChannel : zzTest.Makolab.Fractus.Communication.ISynchronizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SynchronizationServiceClient : System.ServiceModel.ClientBase<zzTest.Makolab.Fractus.Communication.ISynchronizationService>, zzTest.Makolab.Fractus.Communication.ISynchronizationService {
        
        public SynchronizationServiceClient() {
        }
        
        public SynchronizationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SynchronizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynchronizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynchronizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Channels.Message GetData(System.ServiceModel.Channels.Message request) {
            return base.Channel.GetData(request);
        }
        
        public System.ServiceModel.Channels.Message SendData(System.ServiceModel.Channels.Message request) {
            return base.Channel.SendData(request);
        }
    }
}
