using System;
using System.Collections.Generic;
using System.Text;

namespace Makolab.Printing.Fiscal
{
    public enum FiscalExceptionId
    {
        Nr1_RTCClockInit = 1,
        Nr2_CRCError = 2,
        Nr3_ParamQuantity = 3,
        Nr4_DataError = 4,
        Nr5_RTCClockError = 5,
        Nr6_TotalizerError = 6,
        Nr7_DateError = 7,
        Nr8_NotNullTotalizer = 8,
        Nr9_IOError = 9,
        Nr11_PTUError = 11,
        Nr12_HeaderError = 12,
        Nr13_FiscalError = 13,
        Nr16_NameError = 16,
        Nr17_QuantityError = 17,
        Nr18_PTUError = 18,
        Nr19_ValueError_CENA = 19,
        Nr20_ValueError_BRUTTO_RABAT = 20,
        Nr21_TransactionError = 21,
        Nr22_StornoError = 22,
        Nr23_TransactionError = 23,
        Nr25_ErrorCode_cashier_cash = 25,
        Nr26_ValueError_WPLATA = 26,
        Nr27_ValueError_TOTAL_RABAT = 27,
        Nr28_TotalizerError = 28,
        Nr29_TransactionError = 29,
        Nr30_ValueError_WPLATA = 30,
        Nr31_SumError = 31,
        Nr32_SubstractionError = 32,
        Nr33_NameString_nazwa_kasjer_numer_kaucja = 33,
        Nr34_NameOrSumError = 34,
        Nr35_ZeroTotalizerError = 35,
        Nr36_DateError = 36,
        Nr37_OperationError = 37,
        Nr38_NameError = 38,
        Nr39_PTUError = 39,
        Nr40_RAMHeaderError = 40,
        Nr41_CashNumberError = 41,
        Nr42_CashierNumberError = 42,
        Nr43_PairNumberError = 43,
        Nr44_ContractorError = 44,
        Nr45_TeminalError = 45,
        Nr46_CardNameError = 46,
        Nr47_CardNumberError = 47,
        Nr48_DateError = 48,
        Nr49_DateError = 49,
        Nr50_AuthorizationCodeError = 50,
        Nr51_ValueError_KWOTA = 51,
        Nr82_CodeProgrammingNumberExceededError = 82,
        Nr83_DepositError = 83,
        Nr84_DisplayError = 84,
        Nr90_OperationError = 90,
        Nr91_TransactionError = 91,
        Nr92_ArticlesDataBaseOverfilledError = 92,
        Nr93_CancelPaymentError = 93,
        Nr94_MaxSaleValueError = 94,
        Nr95_TransactionError = 95,
        Nr96_TimeoutError = 96,
        Nr97_BatteryLowError = 97,
        Nr98_ServiceError = 98,
        Nr255_UnKnownCommandError = 255,
        UnableToConnectToPrinterError,
        DriverIsNotConfiguredError,
        TimeoutException,
        PrinterDLEError,
        MissingCashierError,
        MissingBillNumberError,
        MissingGrossValueError,
        PrinterPrecisionError,
        NotImplementedFeature,
        ConnectionError

    }
}
