/*
name=[finance].[PaymentSettlement]
version=1.0.1
lastUpdate=2017-01-24 10:37:21
v2eItcutkOwWYVlMuqidPA==
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[finance].[PaymentSettlement]') AND type in (N'U'))
BEGIN
CREATE TABLE [finance].[PaymentSettlement](
	[id] [uniqueidentifier] NOT NULL,
	[date] [datetime] NOT NULL,
	[incomePaymentId] [uniqueidentifier] NOT NULL,
	[outcomePaymentId] [uniqueidentifier] NOT NULL,
	[amount] [numeric](18, 2) NOT NULL,
	[version] [uniqueidentifier] NOT NULL,
	[isAutoGenerated] [bit] NOT NULL,
 CONSTRAINT [PK_PaymentSettlement] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[finance].[PaymentSettlement]') AND name = N'indPaymentSettlement_firstPaymentId')
CREATE NONCLUSTERED INDEX [indPaymentSettlement_firstPaymentId] ON [finance].[PaymentSettlement]
(
	[incomePaymentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[finance].[PaymentSettlement]') AND name = N'indPaymentSettlement_secondPaymentId')
CREATE NONCLUSTERED INDEX [indPaymentSettlement_secondPaymentId] ON [finance].[PaymentSettlement]
(
	[outcomePaymentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[finance].[FK_PaymentSettlement_Payment]') AND parent_object_id = OBJECT_ID(N'[finance].[PaymentSettlement]'))
ALTER TABLE [finance].[PaymentSettlement]  WITH CHECK ADD  CONSTRAINT [FK_PaymentSettlement_Payment] FOREIGN KEY([incomePaymentId])
REFERENCES [finance].[Payment] ([id])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[finance].[FK_PaymentSettlement_Payment]') AND parent_object_id = OBJECT_ID(N'[finance].[PaymentSettlement]'))
ALTER TABLE [finance].[PaymentSettlement] CHECK CONSTRAINT [FK_PaymentSettlement_Payment]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[finance].[FK_PaymentSettlement_Payment1]') AND parent_object_id = OBJECT_ID(N'[finance].[PaymentSettlement]'))
ALTER TABLE [finance].[PaymentSettlement]  WITH CHECK ADD  CONSTRAINT [FK_PaymentSettlement_Payment1] FOREIGN KEY([outcomePaymentId])
REFERENCES [finance].[Payment] ([id])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[finance].[FK_PaymentSettlement_Payment1]') AND parent_object_id = OBJECT_ID(N'[finance].[PaymentSettlement]'))
ALTER TABLE [finance].[PaymentSettlement] CHECK CONSTRAINT [FK_PaymentSettlement_Payment1]
GO
