/*
name=[item].[ItemKey]
version=1.0.1
lastUpdate=2017-01-24 10:37:21
OU5KJMz589ZElOQjkYoFtw==
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[item].[ItemKey]') AND type in (N'U'))
BEGIN
CREATE TABLE [item].[ItemKey](
	[id] [uniqueidentifier] NOT NULL,
	[key] [varchar](50) NOT NULL,
 CONSTRAINT [PK_ItemfKey] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
